<?xml version="1.0"?>
<!-- Laelaps Simulation - Wheel -->
<robot name="laelaps_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="wheel_radius" value="0.055"/> 
  <xacro:property name="wheel_height" value="0.06"/>
  <xacro:property name="wheel_mass" value="2.5"/>
  <xacro:property name="base_x_origin_to_wheel_origin" value="0.10"/> 
  <xacro:property name="base_x_origin_to_wheel_origin_offset" value="-0.015"/> 
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.16"/>
  <xacro:property name="base_z_origin_to_wheel_origin" value="0.00"/>
 
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
             izz="${m*(3*r*r+h*h)/12}" iyz="0"
             iyy="${m*r*r/2}"/>
  </xacro:macro>

  <xacro:macro name="laelaps_wheel" params="fb lr parent translateX translateY flipY">
    <link name="${fb}_${lr}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${flipY*PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://laelaps_description/meshes/wheel_with_rim.stl"/>
          <!-- <cylinder length="${wheel_height}" radius="${wheel_radius}"/> -->
        </geometry>
        <material name="DarkGray"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${flipY*PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0" rpy="${flipY*PI/2} 0 0"/> 
        <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}"/>
      </inertial>
    </link>
    <gazebo reference="${fb}_${lr}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="10000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/DarkGrey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>
    <joint name="${fb}_${lr}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${fb}_${lr}_wheel"/>
      <origin xyz="${translateX * base_x_origin_to_wheel_origin + base_x_origin_to_wheel_origin_offset} ${translateY * base_y_origin_to_wheel_origin} ${base_z_origin_to_wheel_origin}" rpy="0 0 0"/>
      <axis xyz="0 1 0" rpy="0 0 0"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
     </joint>
     <!-- Transmission is important to link the joints and the controller -->
    <transmission name="${fb}_${lr}_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${fb}_${lr}_wheel_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${fb}_${lr}_wheel_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
</robot>
